name: Run Super-Linter and Test

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: Super-Linter
        working-directory: app
        uses: github/super-linter@v3

      - name: Build
        working-directory: app
        run: go build -v ./...

      - name: Test
        working-directory: app
        run: go test -v ./...

