name: Run Test

on: push

jobs:
  test:
    name: Run Test
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: Build
        working-directory: ./app
        run: go build -v ./...

      - name: Test
        working-directory: ./app
        run: go test -v ./... -coverprofile=coverage.txt -covermode=atomic

      - name: Upload coverage report
        uses: codecov/codecov-action@v1
        with:
          token: {{ secrets.CODECOV_TOKEN }}
          directory: ./app
