name: Run Test

on: push

jobs:
  build:
    name: Run Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: Build
        working-directory: ./app
        run: go build -v ./...

      - name: Test
        working-directory: ./app
        run: go test -v ./... -coverprofile=coverage.txt -covermode=atomic

      - name: Upload coverage report
        working-directory: ./app
        uses: codecov/codecov-action@v1.0.2
        with:
          token: {{ secrets.CODECOV_TOKEN }}
          file: ./coverage.txt
          flags: unittests
          name: codecov-umbrella
